services:
  app:
    build:
      context: .
      args:
        VITE_POOL_TYPE: ${VITE_POOL_TYPE}
        VITE_POOL_ADDRESS: ${VITE_POOL_ADDRESS}
        VITE_STRATEGY_ADDRESS: ${VITE_STRATEGY_ADDRESS}
        VITE_DEFAULT_REFERRAL_ADDRESS: ${VITE_DEFAULT_REFERRAL_ADDRESS}
        VITE_WIDGET_TITLE: ${VITE_WIDGET_TITLE}
        VITE_DEFAULT_CHAIN: ${VITE_DEFAULT_CHAIN}
        VITE_SUPPORTED_CHAINS: ${VITE_SUPPORTED_CHAINS}
        VITE_PUBLIC_EL_RPC_URLS_1: ${VITE_PUBLIC_EL_RPC_URLS_1}
        VITE_PUBLIC_EL_RPC_URLS_560048: ${VITE_PUBLIC_EL_RPC_URLS_560048}
        VITE_WALLETCONNECT_PROJECT_ID: ${VITE_WALLETCONNECT_PROJECT_ID}
        VITE_DEVNET_OVERRIDES: ${VITE_DEVNET_OVERRIDES}
        VITE_LOCALE: ${VITE_LOCALE}
    ports:
      - '3017:80'
